### PR TITLE
Added GIF to readme

### PR DESCRIPTION
**Pull request by Naton-1**
I thought it'd be cool to show a prospective user a preview of what the script does. Let me know your thoughts.

### CODE REVIEW

**Comment by TobiasPankner** [comment]
Great idea, I would prefer the gif to be hosted online though.  
If you edit the Readme in github it should automatically upload it. Alternatively you can use Imgur.  
Thanks

**Comment by TobiasPankner** [comment]
By editing in github I mean pasting the image in the online editor

**Comment by Naton-1** [comment]
Done! Is that good?

**Comment by TobiasPankner** [comment]
Yes, perfect. I merged it

**Comment by substantialaim** [comment]
I need some help guys

**Pull request merged**
